CREATE TABLE `cron_job` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `key` varchar(64) DEFAULT NULL,
  `description` varchar(200) DEFAULT NULL,
  `code` varchar(64) DEFAULT NULL,
  `spring_schedule_profile_regex` varchar(64) DEFAULT NULL COMMENT 'renambed from spring_profile_regex',
  `spring_ping_profile_regex` varchar(64) DEFAULT NULL COMMENT 'new column',
  `timeout` varchar(30) DEFAULT NULL COMMENT 'now a varchar column',
  `cron` varchar(64) DEFAULT NULL COMMENT 'now QUARTZ expression, not spring cron',
  `static_args` longtext,
  `leader_enabled` int(1) DEFAULT NULL,
  `leader_root_node` varchar(128) DEFAULT NULL COMMENT 'leave null to use default value',
  `semaphore_enabled` int(1) DEFAULT NULL,
  `semaphore_path` varchar(128) DEFAULT NULL COMMENT 'leave null to use default',
  `thread_pool_size` int(11) DEFAULT NULL,
  `last_run_date` datetime DEFAULT NULL COMMENT 'new column, last time the tast ran',
  `last_run_start_date` datetime DEFAULT NULL,
  `last_successful_run_start_date` datetime DEFAULT NULL COMMENT 'new column, last start time the task ran successfully',
  `created_date` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_date` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `report_mode` enum('OFF','ERRORS_ONLY','EVERY_RUN') NOT NULL DEFAULT 'EVERY_RUN',
  `last_successful_run_date` datetime DEFAULT NULL COMMENT 'new column, last time the task ran successfully',
  `created_by` varchar(64) DEFAULT NULL,
  `modified_by` varchar(64) DEFAULT NULL,
  `modified_by_2` varchar(64) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `code` (`code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
